### ISSUE TITLE
Přechod na Python3

### ISSUE THREAD

**Issue by JanKott** [ThunderFly-aerospace/yagv#1]
YAGV volá explicitně python 2:
#!/usr/bin/env python2

Ale pyglet (který YAGV vyžaduje) v poslední verzi už podporuje jen python ve verzi 3.5 a vyšší:
pyglet 1.5.0

Changes
-------
- Support for Python 2 has been dropped. Python 3.5 is now the minimum supported version.

**Comment by roman-dvorak** [comment]
Aktuální verze je kompatibilní s python3.
